Repository Solvro/backend-translator, pull requests merged in 2025-05, with the labels that each got.

#11 feat: replace urls manually through a table
  .github/workflows/ci.yml
  app/admin/resources/index.ts
  app/admin/resources/url_translations.ts
  app/controllers/translations_controller.ts
  app/models/url_translation.ts
  database/migrations/1744100907830_create_url_translations_table.ts
  package-lock.json
  package.json
  tests/bootstrap.ts
  tests/functional/translations_controller.spec.ts
  tests/setup-db.sh
Labels: size/XL

#12 feat: admin panel relations
  app/admin/resources/index.ts
  app/admin/resources/languages.ts
  app/admin/resources/translations.ts
  app/admin/resources/url_translations.ts
Labels: size/M

#13 fix: update @adminjs/adonis dependency to a fork version
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: size/XS

#14 fix: edge case
  app/controllers/translations_controller.ts
  tests/functional/translations_controller.spec.ts
Labels: size/M
