Repository Solvro/backend-translator, pull requests merged in 2025-04, with the labels that each got.

#3 feat: improve system prompt
  app/controllers/translations_controller.ts
Labels: enhancement, size/S

#4 feat: add specific proper nouns to translation guidelines
  app/controllers/translations_controller.ts
Labels: size/XS

#5 fix: add chunking
  app/controllers/translations_controller.ts
Labels: size/M

#6 fix: update translation guidelines to exclude non-text content from translation
  app/controllers/translations_controller.ts
Labels: size/XS

#7 fix(controller): enhance sentence matching for text chunking in translations
  app/controllers/translations_controller.ts
Labels: size/XS

#8 fix(controller): refine sentence matching logic for improved text chunking
  app/controllers/translations_controller.ts
Labels: size/XS

#9 feat: admin panel
  .env.example
  .gitignore
  adonisrc.ts
  app/admin/auth.ts
  app/admin/component_loader.ts
  app/admin/components/truncated_text.tsx
  app/admin/resources/index.ts
  app/admin/resources/translations.ts
  app/admin/resources/utils/timestamps.ts
  app/controllers/translations_controller.ts
  app/models/user.ts
  commands/create_user.ts
  config/adminjs.ts
  config/session.ts
  database/migrations/1744100907322_create_users_table.ts
  eslint.config.js
  package-lock.json
  package.json
  start/env.ts
  start/kernel.ts
  start/routes.ts
  tsconfig.json
Labels: size/L

#10 fix: do not translate addresses
  app/controllers/translations_controller.ts
  database/migrations/1744100907822_delete_street_translations.ts
Labels: size/M
